---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: win-2008r2-standard-amd64-nocm
    driver:
      box: opentable/win-2008r2-standard-amd64-nocm

suites:
  - name: default
    run_list:
#      - recipe[powershell::powershell3]
      - recipe[ohai_iis::app]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
